apiVersion: v1
kind: Service
metadata:
  annotations:
    publishNotReadyAddresses: "true"
  labels:
    app: easytrack
  name: cassandra
spec:
  clusterIP: None
  ports:
  - port: 9042
  selector:
    app: cassandra
