apiVersion: v1
kind: Service
metadata:
  name: grpc-service
  labels:
    app: easytrack
spec:
  type: LoadBalancer
  selector:
    app: easytrack
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30051
