# Components:
# - PostgreSQL database (postgres)
# - pgAdmin4 database management tool

services:
  et-postgres:
    container_name: et-postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "et-postgres-vol:/var/lib/postgresql/data"
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  et-pgadmin4:
    container_name: et-pgadmin4
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - "et-pgadmin4-vol:/var/lib/pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: easytrack@mail.com
      PGADMIN_DEFAULT_PASSWORD: easytrack

volumes:
  et-postgres-vol:
  et-pgadmin4-vol:

networks:
  default:
    # create network externally: `docker network create et-network`
    name: et-network
    external: true